---
- name : Creating new user
  user :
    name : "{{ sname }}"
    password : "{{ 'Abc123 | password_hash('sha512') }}"
    comment : "sfull"
    shell : /bin/bash
    group : root
    groups : root
    home : /home/{{ sname }}
